version: "3.8"
services:

  redis:
    image: "redis:alpine"

  workercamera:
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/webcam-docker
      - /dev/:/dev/
    command: bash -c "python worker_camera.py"
    privileged: true

  webcamera:
    build: .
    volumes:
      - .:/webcam-docker
    ports:
      - "5000:5000"
